AWSTemplateFormatVersion: '2010-09-09'

Description: >
  Segment Lambda Destination
  https://segment.com/docs/destinations/amazon-lambda/

Globals:
  Function:
    Runtime: nodejs10.x
    Timeout: 3

Outputs:
  LambdaARN:
    Value: !GetAtt ProcessEventsFunction.Arn

  RoleARN:
    Value: !GetAtt InvokeLambdaRole.Arn

Resources:
  InvokeLambdaPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: segment-invoke-lambda
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: lambda:InvokeFunction
          Resource: !GetAtt ProcessEventsFunction.Arn
      Roles:
        - !Ref InvokeLambdaRole

  InvokeLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            AWS: arn:aws:iam::595280932656:root
          Action: sts:AssumeRole

  ProcessEventsFunction:
    Properties:
      CodeUri: .
      Handler: index.processEvents
    Type: AWS::Serverless::Function

Transform: AWS::Serverless-2016-10-31
